"""add language to survey responses

Revision ID: 20d3d76d5811
Revises: 5300ed5d1e11
Create Date: 2026-06-09 11:46:34.409204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "20d3d76d5811"
down_revision: Union[str, None] = "5300ed5d1e11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("survey_responses", sa.Column("language", sa.String(length=10), nullable=False, server_default="en"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("survey_responses", "language")
    # ### end Alembic commands ###
