"""create bulk communication tables

Revision ID: 945369148502
Revises: b8c9d0e1f2a3
Create Date: 2026-05-18 18:06:21.236061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945369148502'
down_revision: Union[str, None] = 'b8c9d0e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['bulk_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('uq_plans_code', 'plans', type_='unique')
    op.drop_index('ix_plans_code', table_name='plans')
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=True)
    op.drop_constraint('uq_subscriptions_tenant_id', 'subscriptions', type_='unique')
    op.drop_index('ix_subscriptions_tenant_id', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=True)
    op.drop_constraint('tenants_slug_key', 'tenants', type_='unique')
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_index('ix_uploaded_files_tenant_id', table_name='uploaded_files')
    op.drop_constraint('user_profiles_email_key', 'user_profiles', type_='unique')
    op.drop_index('ix_user_profiles_email', table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.drop_constraint('waitlist_entries_email_key', 'waitlist_entries', type_='unique')
    op.drop_index('ix_waitlist_entries_email', table_name='waitlist_entries')
    op.create_index(op.f('ix_waitlist_entries_email'), 'waitlist_entries', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_entries_email'), table_name='waitlist_entries')
    op.create_index('ix_waitlist_entries_email', 'waitlist_entries', ['email'], unique=False)
    op.create_unique_constraint('waitlist_entries_email_key', 'waitlist_entries', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.create_index('ix_user_profiles_email', 'user_profiles', ['email'], unique=False)
    op.create_unique_constraint('user_profiles_email_key', 'user_profiles', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_uploaded_files_tenant_id', 'uploaded_files', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=False)
    op.create_unique_constraint('tenants_slug_key', 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.create_index('ix_subscriptions_tenant_id', 'subscriptions', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_subscriptions_tenant_id', 'subscriptions', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.create_index('ix_plans_code', 'plans', ['code'], unique=False)
    op.create_unique_constraint('uq_plans_code', 'plans', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_table('bulk_recipients')
    op.drop_table('bulk_campaigns')
    # ### end Alembic commands ###
