"""add_performance_indexes

Revision ID: f5ca161f61a9
Revises: 8a7b6c5d4e3f
Create Date: 2026-05-26 13:18:27.455995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5ca161f61a9'
down_revision: Union[str, None] = '8a7b6c5d4e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_survey_answers_question_id'), 'survey_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_survey_shares_shared_with'), 'survey_shares', ['shared_with'], unique=False)
    op.create_index(op.f('ix_surveys_created_by'), 'surveys', ['created_by'], unique=False)
    op.create_index(op.f('ix_surveys_tenant_id'), 'surveys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_created_by'), 'uploaded_files', ['created_by'], unique=False)
    op.create_index(op.f('ix_uploaded_files_tenant_id'), 'uploaded_files', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_tenant_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_created_by'), table_name='uploaded_files')
    op.drop_index(op.f('ix_surveys_tenant_id'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_created_by'), table_name='surveys')
    op.drop_index(op.f('ix_survey_shares_shared_with'), table_name='survey_shares')
    op.drop_index(op.f('ix_survey_answers_question_id'), table_name='survey_answers')
    # ### end Alembic commands ###
