"""add_bulk_campaigns

Revision ID: fc3edd03e227
Revises: 945369148502
Create Date: 2026-05-18 19:49:45.213059

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc3edd03e227"
down_revision: Union[str, None] = "945369148502"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bulk_campaigns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "campaign_type",
            sa.Enum("email", "whatsapp", name="bulkcampaigntypeenum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "sent", "failed", name="bulkcampaignstatusenum"),
            nullable=True,
        ),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("message_body", sa.Text(), nullable=False),
        sa.Column("total_recipients", sa.Integer(), nullable=True),
        sa.Column("successful_sends", sa.Integer(), nullable=True),
        sa.Column("failed_sends", sa.Integer(), nullable=True),
        sa.Column("recipient_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["user_profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bulk_campaigns_tenant_id"),
        "bulk_campaigns",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bulk_campaigns_tenant_id"), table_name="bulk_campaigns")
    op.drop_table("bulk_campaigns")
    # ### end Alembic commands ###
