name: CDK Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: 'ap-south-1'
    secrets:
      AWS_ROLE_TO_ASSUME:
        required: true

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Simple Check
        run: echo "CDK Deploy for ${{ inputs.environment }}"
