name: AxioraPulse Master Pipeline

on:
  push:
    branches:
      - fix/workflow-paths-syntax
    paths:
      - '.github/workflows/**'

jobs:
  # 1. Quality Gate
  ci-quality-gate:
    uses: ./.github/workflows/ci.yml
    with:
      check_backend: true
      check_frontend: true

  # 2. QA Environment Deployment
  deploy-qa-infra:
    needs: ci-quality-gate
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.target_env == 'qa')
    uses: ./.github/workflows/cdk.yml
    with:
      environment: qa
    secrets: inherit
